version: "4.0"

networks:
  net-dns:
    ipam:
      config:
        - subnet: 10.128.10.0/24
          gateway: 10.128.10.254
  net-clients:
    ipam:
      config:
        - subnet: 10.128.20.0/24
          gateway: 10.128.20.254

services:
  ns1:
    image: ubuntu:24.04
    container_name: ns1
    cap_add:
      - NET_ADMIN
    networks:
      net-dns:
        ipv4_address: 10.128.10.11
    volumes:
      - ./ns1/bind:/config/bind:ro
      - ./ns1/init.sh:/init.sh
    command: bash /init.sh

  ns2:
    image: ubuntu:24.04
    container_name: ns2
    cap_add:
      - NET_ADMIN
    networks:
      net-dns:
        ipv4_address: 10.128.10.12
    volumes:
      - ./ns2/bind:/config/bind:ro
      - ./ns2/init.sh:/init.sh
    command: bash /init.sh

  host1:
    image: ubuntu:24.04
    container_name: host1
    cap_add:
      - NET_ADMIN
    networks:
      net-clients:
        ipv4_address: 10.128.20.101
    volumes:
      - ./host1/init.sh:/init.sh
    command: bash /init.sh

  host2:
    image: ubuntu:24.04
    container_name: host2
    cap_add:
      - NET_ADMIN
    networks:
      net-clients:
        ipv4_address: 10.128.20.102
    volumes:
      - ./host2/init.sh:/init.sh
    command: bash /init.sh

  router:
    image: alpine:latest
    container_name: router
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      net-dns:
        ipv4_address: 10.128.10.1
      net-clients:
        ipv4_address: 10.128.20.1
    command: sleep infinity
    restart: unless-stopped